### ISSUE TITLE
Deprecation message in Ember.js 1.13

### ISSUE THREAD

**Issue by akshayrawat** [paddle8/ember-plupload#23]
I'm seeing this deprecation message after upgrading to Ember.js 1.13. I'm not entirely sure if its my code or the addon. So I just wanted to confirm this with someone using this add-on with Ember.js 1.13

> DEPRECATION: You modified ShouldDisplay(dropzone.enabled) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4567/assets/vendor.js:59061:35)
        at http://localhost:4567/assets/vendor.js:21874:32
        at Object.Stream.notifySubscribers (http://localhost:4567/assets/vendor.js:31130:11)
        at Object.Stream.notifyExcept (http://localhost:4567/assets/vendor.js:31070:14)
        at Object.Stream.notify (http://localhost:4567/assets/vendor.js:31064:12)
        at Object.Stream.notifySubscribers (http://localhost:4567/assets/vendor.js:31132:20)
        at Object.Stream.notifyExcept (http://localhost:4567/assets/vendor.js:31070:14)
        at Object.Stream.notify (http://localhost:4567/assets/vendor.js:31064:12)
        at Object.Stream.notifySubscribers (http://localhost:4567/assets/vendor.js:31132:20)
        at Object.Stream.notifyExcept (http://localhost:4567/assets/vendor.js:31070:14)
        at Object.Stream.notify (http://localhost:4567/assets/vendor.js:31064:12)

**Comment by tim-evans** [comment]
I think this is fixed in a newer version of the addon.

Could you confirm that you're above 0.6.19? (https://github.com/paddle8/ember-plupload/blob/master/CHANGELOG.md#0619-june-12-2015)

**Comment by tim-evans** [comment]
Please comment if this is still an issue.
